name: Deploy docs

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Graphviz
        run: |
          sudo apt update
          sudo apt install -y graphviz

      # until ubuntu 26.04 release?
      - name: Install Doxygen
        run: |
          doxygen_ver=1.15.0
          wget https://www.doxygen.nl/files/doxygen-${doxygen_ver}.linux.bin.tar.gz
          tar -xzf doxygen-${doxygen_ver}.linux.bin.tar.gz
          sudo mv doxygen-${doxygen_ver}/bin/doxygen /usr/local/bin/
          rm -rf doxygen-${doxygen_ver}

      - name: Generate docs
        run: doxygen

      - name: Set up Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./out/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
